### ISSUE TITLE
Improvements for packagers

### ISSUE THREAD

**Issue by SpotlightKid** [rubik/mando#40]
To help packing mando for distributions, could you please:

* include `LICENSE` in `MANIFEST.in` so that it gets included in the source distribution
* make sure to tag releases, so that we can be notified by Github and check which is the latest version?

Also, is it really necessary to install the `mando.tests` package by default? This comes with additional dependencies (Sphinx and paramunittest), which are not declared in the `setup.py`. Couldn't this be moved into the project root?

(For context, I'm maintaining https://aur.archlinux.org/packages/python-mando/)

**Comment by rubik** [comment]
Done. I'll make sure to tag releases in the future. I think I skipped one? The last one is definitely tagged, though.
As for the tests, they were originally at the root of the project and were moved because this way they are automatically included in the source distribution. There's no need to declare the test dependencies in setup.py as they are optional. If one really wants to run the tests can install the dependencies separately.

**Comment by SpotlightKid** [comment]
Ah, now I see. There are tags for 0.5 and 0.3.2 but Github sorta hid them (collapsed them) from me, because the tag for 0.3.1 is still flagged as the latest release.

**Comment by SpotlightKid** [comment]
I usually rely double check with the latest version available on PyPI, so in this case that was a bit confusing, because I didn't see the the 0.5 tag and thought there was a mismatch.

**Comment by rubik** [comment]
I see, I've made 0.5 the latest release.
