### ISSUE TITLE
Variadic arguments and internal representation

### ISSUE THREAD

**Issue by acetylen** [rubik/mando#48]
I noticed that the internal representation of arguments about to be passed to a function is always a list. This gives the side-effect that a variadic `*arg` must always be last in the funciton signature, which goes against PEP8. Keyword arguments should *follow* the star arg.

 With #47 merged, that implementation could be split up into the more traditional `*args, **kwargs`. I have [a proof-of-concept implementation of this in the branch `varargs` in my fork of mando](https://github.com/acetylen/mando/blob/eafd0d834c69bb541e479b98d6d36371c01dd347/mando/core.py#L195), but rewriting all the tests would take a lot of time.

Is this a desirable change?

**Comment by rubik** [comment]
I see your point, but I don't remember that recommendation in PEP8, and a quick search does not yield results (I searched for all instances of `*`, `varargs`, `star`).

It's done like that because it's the natural way of expressing a command with options that might take repeated arguments. E.g. a command like `ls`, that takes options and then a list of paths of indeterminate length.

**Comment by acetylen** [comment]
Yeah, I definitely see the rationale behind it when it comes to a command-line program.

As for the ordering, I should of course have linked to something backing me up. It's not in PEP8, it's in the [spec](https://docs.python.org/3/reference/expressions.html#calls). However, I don't quite understand the formulation in the sentence about how keyword arguments are converted to positional ones. Maybe it's best to not mess with something that works :)

**Comment by rubik** [comment]
@acetylen I agree. Since it works and it maintains the similarities with CLI usage, I'm inclined not to change it.
